INSERT INTO trumpisms (quote) VALUES ("An extremely credible source has called my office and told me that Barack Obama's birth certificate is a fraud.");
INSERT INTO trumpisms (quote) VALUES ("You know, it really doesn't matter what the media write as long as you've got a young and beautiful piece of ass.");
INSERT INTO trumpisms (quote) VALUES ("I will build a great wall - and nobody builds walls better than me, believe me - and I'll build them very inexpensively. I will build a great, great wall on our southern border, and I will make Mexico pay for that wall. Mark my words.");
INSERT INTO trumpisms (quote) VALUES ("If I were running The View, I'd fire Rosie O'Donnell. I mean, I'd look at her right in that fat, ugly face of her's, I'd say 'Rosie, you're fired.'");
INSERT INTO trumpisms (quote) VALUES ("The beauty of me is that I'm very rich.");
INSERT INTO trumpisms (quote) VALUES ("I've said if Ivanka weren't my daughter, perhaps I'd be dating her.");
INSERT INTO trumpisms (quote) VALUES ("I have never seen a thin person drinking Diet Coke.");
INSERT INTO trumpisms (quote) VALUES ("The point is, you can never be too greedy.");
INSERT INTO trumpisms (quote) VALUES ("I have so many fabulous friends who happen to be gay, but I am a traditionalist.");
INSERT INTO trumpisms (quote) VALUES ("Look at those hands, are they small hands?");
INSERT INTO trumpisms (quote) VALUES ("I guarantee you there's no problem. I guarantee.");
INSERT INTO trumpisms (quote) VALUES ("I have a great relationship with the Mexican people.");
INSERT INTO trumpisms (quote) VALUES ("Sometimes by losing a battle you find a new way to win the war.");
INSERT INTO trumpisms (quote) VALUES ("Do you mind if I sit back a little? Because your breath is very bad.");
INSERT INTO trumpisms (quote) VALUES ("As long as you're going to be thinking anyway, think big.");
INSERT INTO trumpisms (quote) VALUES ("I like thinking big. If you're going to be thinking anything, you might as well think big.");
INSERT INTO trumpisms (quote) VALUES ("Without passion you don't have energy, without energy you have nothing.");
INSERT INTO trumpisms (quote) VALUES ("Private jets cost a lot of money.");
INSERT INTO trumpisms (quote) VALUES ("I don't like losers.");
INSERT INTO trumpisms (quote) VALUES ("I like people who weren't captured.");
INSERT INTO trumpisms (quote) VALUES ("All of the women on The Apprentice flirted with me, conciously or unconciously. That's to be expected.");
INSERT INTO trumpisms (quote) VALUES ("Owning a great golf course gives you great power.");
INSERT INTO trumpisms (quote) VALUES ("We need a great president.");
INSERT INTO trumpisms (quote) VALUES ("It's not like I'm anti-China. I just think it's ridiculous that we allow them to do what they're doing to this country, with the manipulation of the currency, that you write about and understand, and all of the other things that they do.");
INSERT INTO trumpisms (quote) VALUES ("You know that ISIS wants to go in and take over the Vatican? You have heard that. You know, that's a dream of theirs, to go into Italy.");
INSERT INTO trumpisms (quote) VALUES ("Mexico's making a fortune off the United States.");
INSERT INTO trumpisms (quote) VALUES ("I understand the military. I know the military.");
INSERT INTO trumpisms (quote) VALUES ("I'm very strongly against tax increases.");
INSERT INTO trumpisms (quote) VALUES ("The wall just got ten feet taller, believe me.");
INSERT INTO trumpisms (quote) VALUES ("I would build a great wall.");
INSERT INTO trumpisms (quote) VALUES ("Nobody builds walls better than me, believe me.");
INSERT INTO trumpisms (quote) VALUES ("I will build a great, great wall on our Southern border.");
INSERT INTO trumpisms (quote) VALUES ("Mexico's going to pay for the wall.");
INSERT INTO trumpisms (quote) VALUES ("We're going to do a wall; we're going to have a big, fat beautiful door on the wall; we're going to have people come in, but they're going to come in legally.");
INSERT INTO trumpisms (quote) VALUES ("I love the poorly educated.");
INSERT INTO trumpisms (quote) VALUES ("You are the single biggest liar, you're probably worse than Jeb Bush.");
INSERT INTO trumpisms (quote) VALUES ("I call him Lyin' Ted. He holds the Bible high and then he puts the Bible down and then he lies. Lyin' Ted.");
INSERT INTO trumpisms (quote) VALUES ("Don't worry about it, Little Marco.");
INSERT INTO trumpisms (quote) VALUES ("I used to use the word incompetent, now I just call him stupid.");
INSERT INTO trumpisms (quote) VALUES ("I know words, I have the best words.");
INSERT INTO trumpisms (quote) VALUES ("That's because he got Ben Carson's votes, by the way.");
INSERT INTO trumpisms (quote) VALUES ("Our country doesn't win anymore.");
INSERT INTO trumpisms (quote) VALUES ("We don't win anymore. We lose on trade, we lose with ISIS, we lose with one of the worst deals I've ever seen negotiated of any kind - that's our recent catastrophe with Iran.");
INSERT INTO trumpisms (quote) VALUES ("If I'm elected President, we will win and we will win and we will win.");
INSERT INTO trumpisms (quote) VALUES ("Make America great again.");
INSERT INTO trumpisms (quote) VALUES ("I love winning with women.");
INSERT INTO trumpisms (quote) VALUES ("Obama just endorsed Crooked Hillary. He wants four more years of Obama - but nobody else does!");
